### ISSUE TITLE
loading caibx header failed

### ISSUE THREAD

**Issue by devhigh29** [florolf/casync-nano#3]
While trying to extract, i am getting the following error

sudo csn /tmp/foo.caibx /dev/mmcblk1p6 http://192.168.0.93:8080/default.castr/
caibx.c:load_index_header:65	unsupported feature set: 0xa000000000000000
main.c:csn:124	loading caibx header failed
main.c:main:270	initializing synchronization process failed

The same caibx file is working with casync, i only see this error with casync-nano

**Comment by florolf** [comment]
The feature flag set displayed in the error message means that you're trying to extract a caibx file that uses SHA512/256 hashes. casync-nano only supports SHA256 because on the class of devices it is meant for (roughly 32bit ARM processors), SHA512 is significantly slower than SHA256. You can get `casync make` to generate compatible indices by using `--digest=sha256`. Note that while this will result in the same chunks as in the default settings, but they will have different IDs because of the different hash algorithm.

**Comment by devhigh29** [comment]
Thanks, it solved the issue.
